### ISSUE TITLE
Different behavior when casting objective values: execute(Callable) vs execute(str)

### ISSUE THREAD

**Issue by styamamoto** [aistairc/aiaccel#168]
In aiaccel.util.aiaccel.Run, different behavior can be occur when calculated objective value is cast with `y_data_type` as `None`.
When using `execute(func, y_data_type=None)` (first argument is python function), the result type is not cast.
On the other hand, when using `execute("command", y_data_type=None)` (first argument is command), result type is forced to be cast as float.
Which is intended behavior?

cast_y is;
https://github.com/aistairc/aiaccel/blob/b40f0cb1efefdca54f5e95392998c0e6a4a5caa9/aiaccel/util/aiaccel.py#L254-L256
when using `execute(func)`
https://github.com/aistairc/aiaccel/blob/b40f0cb1efefdca54f5e95392998c0e6a4a5caa9/aiaccel/util/aiaccel.py#L280-L281
when using `execute("command")`
https://github.com/aistairc/aiaccel/blob/b40f0cb1efefdca54f5e95392998c0e6a4a5caa9/aiaccel/util/aiaccel.py#L315-L316

**Comment by aramoto99** [comment]
@styamamoto

Both processes are as intended.

- execute(func, y_data_type=None)
The data type of the objective function output value depends on the user program; if y_data_type=None, cast is not performed.

- execute("command", y_data_type=None)
The result of the objective function is extracted from the stdout, but it must be cast to flaot because it is obtained in str type (when Nelder-Mead is used, return values of str type cannot be used). Therefore, if the type specified in `y_data_type` does not exist, it is set to float by default.

<hr>

どちらの処理も，意図通りです．

- execute(func, y_data_type=None)
目的関数の出力値のデータ型は，ユーザープログラムに依存します．y_data_type=Noneの場合，castを実施しません．

- execute("command", y_data_type=None)
目的関数の結果をsubprocessで実行し標準出力から結果を抽出しますが，str型で取得するため, flaotにcastする必要があります(Nelder-Mead使用時はstr型の戻り値を使用できない)．そのため，`y_data_type`で指定の型が存在しない場合はデフォルトでfloatにしています．

**Comment by styamamoto** [comment]
@aramoto99 

Thank you for your kind explanation.
I have forgotten the difference between a return from function and a stdout.

---

ありがとうございます．
関数の戻り値と標準出力の違いを失念しておりました．
